samples: "config/samples.tsv"
ragtag_ref: "resources/reference.fna"
window_size: 100
spades:
  extra: "--careful"

fastp:
  extra: "--detect_adapter_for_pe"

iqtree:
  extra: "-bb 1000 -m TEST"

contamination_fasta: "resources/contamination/contaminants.fa"