samples: "config/samples.tsv"
ragtag_ref: "resources/reference.fna"
window_size: 100
spades:
  extra: "--careful"

fastp:
  extra: "--detect_adapter_for_pe"

iqtree:
  extra: "-bb 1000 -m TEST"

contamination_fastas:
  - "resources/contamination/FASTA/Homo_sapiens.GRCh38.dna.alt.fa"
  - "resources/contamination/FASTA/GCA_000935865.1_ASM93586v1_genomic.fna"
  - "resources/contamination/FASTA/GCF_000935865.1_ASM93586v1_genomic.fna"

kraken2_db: "https://genome-idx.s3.amazonaws.com/kraken/k2_standard_08gb_20250402.tar.gz"

use_reference: true #false
use_polished_assembly: true #false